paths:
    /ai/search:
        post:
            tags:
                - AI
            summary: 향수 검색
            parameters:
                - name: search
                  in: body
                  required: true
                  schema:
                      properties:
                          search:
                              type: string
                              description: 검색 텍스트
                              example: 코롱

            responses:
                "200":
                    description: 검색 성공
                    schema:
                        type: object
                        properties:
                            status:
                                type: integer
                                example: 200
                            isSuccess:
                                type: boolean
                                example: true
                            code:
                                type: integer
                                example: 2000
                            message:
                                type: string
                                example: "success!"
                            result:
                                type: array
                                example:
                                    - perfumeID: 6
                                      name: "Acqua di Colonia Freesia Cologne"
                                      nameKor: "아쿠아 디 콜라니아 프리지아 코롱"
                                      description: "가장 깨끗한 '비누향기'로 특히 국내에서\n산마노 유행을 불러일으킨 장본인, 프리지아 입니다\n\n화창한 하늘에 걸린 구름을 꺼내 덮을 수 있는 솜 이불로 만들어\n하얘질 때까지 빤 후, 온몸에 천천히 두른 것 같은 비누의 뽀송함이 느껴집니다\n\n특히 갓 빨아낸 호텔 수건에서 느껴질법한 특유의 폭닥함을\n아주 그대로 담고 있는 고급스러움까지 느껴지네요\n\n비누 향기의 대표주자이기 때문에\n호불호 없는 선물로도 데일리로도 매우 좋습니다"
                                      ingredients: "Main\n프리지아\n\nSingle Notes\n프리지아\n\n오 드 코롱 (3~ 7시간)\n계절 사계절 데일리"
                                      brand: "산타마리아 노벨라"
                                      imageUrl: "uploads/6.png"
                                      category:
                                          - "플로럴"
                                    - perfumeID: 7
                                      name: "Wood Sage & Sea Salt Cologne"
                                      nameKor: "우드 세이지 & 씨 솔트 코롱"
                                      description: "조말론 베스트 셀러, 바람이 부는 해변가에서 바람을 맞을 때\n느껴지는 잔잔함, 쏠쏠함, 모던함을 그린 <우드세이지 & 씨솔트>입니다.\n\n마치 잘게 부서진 해변가의 부드러운 모래알맹이가\n바다에서 부는 특유의 시원하고 짭짜름한 공기의 향기와 섞여서 내 몸을 가볍게 훑고 지나가는 듯한 평화로움이 느껴지네요\n\n흔히 말하는 세련됨, 모던한 감수성이 물씬 풍겨\n데일리로 편하게, 꾸민 듯 안 꾸민 듯 공용으로 사용하기 정말 좋습니다."
                                      ingredients: "Main\n암브레트 시드, 바다소금, 세이지, 해초, 자몽\n\nSingle Notes\n암브레트 시드, 바다소금, 세이지, 해초, 자몽\n\n오 드 코롱 (2~6시간)\n계절 사계절 데일리"
                                      brand: "조말론"
                                      imageUrl: "uploads/7.png"
                                      category:
                                          - "시트러스"
                                          - "마린"
                "400":
                    description: 잘못된 요청
                    schema:
                        type: object
                        properties:
                            status:
                                type: integer
                                example: 400
                            isSuccess:
                                type: boolean
                                example: false
                            code:
                                type: integer
                                example: COMMON001
                            message:
                                type: string
                                example: 잘못된 요청입니다

                "500":
                    description: 서버 에러
                    schema:
                        type: object
                        properties:
                            status:
                                type: integer
                                example: 500
                            isSuccess:
                                type: boolean
                                example: false
                            code:
                                type: integer
                                example: COMMON000
                            message:
                                type: string
                                example: 서버 에러, 관리자에게 문의 바랍니다.
    /ai/recommend:
        get:
            tags:
                - AI
            summary: 향수 추천
            parameters:
                - name: userId
                  in: header
                  required: false

            responses:
                "200":
                    description: 로그인 유저 추천 성공
                    schema:
                        type: object
                        properties:
                            status:
                                type: integer
                                example: 200
                            isSuccess:
                                type: boolean
                                example: true
                            code:
                                type: integer
                                example: 2000
                            message:
                                type: string
                                example: "success!"
                            result:
                                type: array
                                example:
                                    - perfumeID: 6
                                      name: "Acqua di Colonia Freesia Cologne"
                                      nameKor: "아쿠아 디 콜라니아 프리지아 코롱"
                                      description: "가장 깨끗한 '비누향기'로 특히 국내에서\n산마노 유행을 불러일으킨 장본인, 프리지아 입니다\n\n화창한 하늘에 걸린 구름을 꺼내 덮을 수 있는 솜 이불로 만들어\n하얘질 때까지 빤 후, 온몸에 천천히 두른 것 같은 비누의 뽀송함이 느껴집니다\n\n특히 갓 빨아낸 호텔 수건에서 느껴질법한 특유의 폭닥함을\n아주 그대로 담고 있는 고급스러움까지 느껴지네요\n\n비누 향기의 대표주자이기 때문에\n호불호 없는 선물로도 데일리로도 매우 좋습니다"
                                      ingredients: "Main\n프리지아\n\nSingle Notes\n프리지아\n\n오 드 코롱 (3~ 7시간)\n계절 사계절 데일리"
                                      brand: "산타마리아 노벨라"
                                      imageUrl: "uploads/6.png"
                                      category:
                                          - "플로럴"
                                    - perfumeID: 7
                                      name: "Wood Sage & Sea Salt Cologne"
                                      nameKor: "우드 세이지 & 씨 솔트 코롱"
                                      description: "조말론 베스트 셀러, 바람이 부는 해변가에서 바람을 맞을 때\n느껴지는 잔잔함, 쏠쏠함, 모던함을 그린 <우드세이지 & 씨솔트>입니다.\n\n마치 잘게 부서진 해변가의 부드러운 모래알맹이가\n바다에서 부는 특유의 시원하고 짭짜름한 공기의 향기와 섞여서 내 몸을 가볍게 훑고 지나가는 듯한 평화로움이 느껴지네요\n\n흔히 말하는 세련됨, 모던한 감수성이 물씬 풍겨\n데일리로 편하게, 꾸민 듯 안 꾸민 듯 공용으로 사용하기 정말 좋습니다."
                                      ingredients: "Main\n암브레트 시드, 바다소금, 세이지, 해초, 자몽\n\nSingle Notes\n암브레트 시드, 바다소금, 세이지, 해초, 자몽\n\n오 드 코롱 (2~6시간)\n계절 사계절 데일리"
                                      brand: "조말론"
                                      imageUrl: "uploads/7.png"
                                      category:
                                          - "시트러스"
                                          - "마린"

                "400":
                    description: 잘못된 요청
                    schema:
                        type: object
                        properties:
                            status:
                                type: integer
                                example: 400
                            isSuccess:
                                type: boolean
                                example: false
                            code:
                                type: integer
                                example: COMMON001
                            message:
                                type: string
                                example: 잘못된 요청입니다

                "500":
                    description: 서버 에러
                    schema:
                        type: object
                        properties:
                            status:
                                type: integer
                                example: 500
                            isSuccess:
                                type: boolean
                                example: false
                            code:
                                type: integer
                                example: COMMON000
                            message:
                                type: string
                                example: 서버 에러, 관리자에게 문의 바랍니다.
