paths:
  /{PerfumeID}/getPerfumes:
    get:
      tags:
        - Perfume
      summary: 향수 상세 정보 조회 로직
      parameters:
        - name: PerfumeID
          in: path
          schema:
            type: integer
          required: true
      responses:
        "200":
          description: 향수 상세 정보 조회 성공
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: array
                example: { "perfume_contentsData": [{ "name": "Eau Duelle", "nameKor": "오 듀엘르", "description": "오 듀엘르는 바닐라 깍지가 고아, 카르타고, 베니스, 바빌론 등의 향신료 항로를 따라 가는, 상상 속의 여행을 표현한 향입니다.", "imageUrl": "uploads/1.png" }] }

        "400":
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        "500":
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
  /{PerfumeID}/getCategories:
    get:
      tags:
        - Perfume
      summary: 향수 카테고리 정보 조회 로직
      parameters:
        - name: PerfumeID
          in: path
          schema:
            type: integer
          required: true
      responses:
        "200":
          description: 향수 카테고리 정보 조회 성공
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: array
                example: { "category_contentsData": [{ "keyword": "우디" }] }

        "400":
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        "500":
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
  /{PerfumeID}/write/{UserID}:
    post:
      tags:
        - Perfume
      summary: 향수 코멘트 작성
      parameters:
        - name: PerfumeID
          in: path
          required: true
          schema:
            type: integer
          description: 작성하려는 향수의 번호
        - name: UserID
          in: path
          required: true
          schema:
            type: integer
          description: 작성하려는 사용자의 ID
        - name: Comment
          in: body
          required: true
          schema:
            properties:
              Content:
                type: string
                description: 향수 코멘트 내용
                example: perfume content
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
          description: Bearer token 작성하기
      responses:
        "200":
          description: 향수 코멘트 작성 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: object
                example: { "UserID": 1, "PerfumeID": 1, "Content": "perfume content" }

        "400":
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        "500":
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
  /{PerfumeID}/delete/{UserID}/{CommentID}:
    delete:
      tags:
        - Perfume
      summary: 향수 코멘트 삭제
      parameters:
        - name: PerfumeID
          in: path
          required: true
          schema:
            type: integer
          description: 삭제하려는 후기의 향수의 번호
        - name: UserID
          in: path
          required: true
          schema:
            type: integer
          description: 삭제하려는 후기의 사용자의 번호
        - name: CommentID
          in: path
          required: true
          schema:
            type: integer
          description: 삭제하려는 후기의 후기의 번호
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
          description: Bearer token 작성하기
      responses:
        "200":
          description: 향수 코멘트 삭제 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: object

        "400":
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        "500":
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
  /{PerfumeID}/readUser:
    get:
      tags:
        - Perfume
      summary: 향수 코멘트 조회 (로그인 유저)
      parameters:
        - name: PerfumeID
          in: path
          required: true
          schema:
            type: integer
          description: 조회하려는 후기의 향수의 번호
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
          description: Bearer token 작성하기
      responses:
        "200":
          description: 향수 코멘트 조회 (로그인 유저) 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: object

        "400":
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        "500":
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
  /{PerfumeID}/read:
    get:
      tags:
        - Perfume
      summary: 향수 코멘트 조회 (비로그인 유저)
      parameters:
        - name: PerfumeID
          in: path
          required: true
          schema:
            type: integer
          description: 조회하려는 후기의 향수의 번호
      responses:
        "200":
          description: 향수 코멘트 조회 (비로그인 유저) 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: object

        "400":
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        "500":
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
  /{PerfumeID}/likePerfumes/{UserID}:
    patch:
      tags:
        - Perfume
      summary: 향수 찜하기 기능
      parameters:
        - name: PerfumeID
          in: path
          required: true
          schema:
            type: integer
          description: 찜하려는 향수의 번호
        - name: UserID
          in: path
          required: true
          schema:
            type: integer
          description: 찜하는 사용자의 번호
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
          description: Bearer token 작성하기
      responses:
        "200":
          description: 향수 찜하기 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: object

        "400":
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        "500":
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
