paths:
  /{Name}/getPerfumes:
    get:
      tags:
        - Perfume
      summary: 향수 상세 정보 조회
      parameters:
        - name: Name
          in: path
          schema:
            type: string
          required: true
      responses:
        "200":
          description: 향수 상세 정보 조회 성공
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: array
                example: { "perfume_contentsData": [{ "name": "Eau Duelle", "nameKor": "오 듀엘르", "description": "오 듀엘르는 바닐라 깍지가 고아, 카르타고, 베니스, 바빌론 등의 향신료 항로를 따라 가는, 상상 속의 여행을 표현한 향입니다.", "imageUrl": "uploads/1.png" }] }

        "400":
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        "500":
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
  /{Name}/getCategories:
    get:
      tags:
        - Perfume
      summary: 향수 카테고리 정보 조회
      parameters:
        - name: Name
          in: path
          schema:
            type: string
          required: true
      responses:
        "200":
          description: 향수 카테고리 정보 조회 성공
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: array
                example: { "category_contentsData": [{ "keyword": "우디" }] }

        "400":
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        "500":
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
  /{Name}/getLikes:
    get:
      tags:
        - Perfume
      summary: 향수 찜 정보 조회
      security:
        - BearerAuth: []
      parameters:
        - name: Name
          in: path
          schema:
            type: string
          required: true
      responses:
        "200":
          description: 향수 찜 정보 조회 성공
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: array
                example: { "like_contentsData": [{ "status": "A" }] }

        "400":
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        "500":
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
  /{Name}/write:
    post:
      tags:
        - Perfume
      summary: 향수 코멘트 작성
      security:
        - BearerAuth: []
      parameters:
        - name: Name
          in: path
          required: true
          schema:
            type: string
          description: 작성하려는 향수의 이름
        - name: Comment
          in: body
          required: true
          schema:
            properties:
              Content:
                type: string
                description: 향수 코멘트 내용
                example: perfume content
      responses:
        "200":
          description: 향수 코멘트 작성 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "write success!"
              data:
                type: object
                example: { "UserID": 1, "Name": "for Her", "Content": "perfume content" }

        "400":
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        "500":
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
  /{Name}/delete/{Content}:
    delete:
      tags:
        - Perfume
      summary: 향수 코멘트 삭제
      security:
        - BearerAuth: []
      parameters:
        - name: Name
          in: path
          required: true
          schema:
            type: string
          description: 삭제하려는 후기의 향수의 이름
        - name: Content
          in: path
          required: true
          schema:
            type: integer
          description: 삭제하려는 후기의 내용
      responses:
        "200":
          description: 향수 코멘트 삭제 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "delete success!"
              data:
                type: object

        "400":
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        "500":
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
  /{Name}/readUser:
    get:
      tags:
        - Perfume
      summary: 향수 코멘트 조회 (로그인 유저)
      security:
        - BearerAuth: []
      parameters:
        - name: Name
          in: path
          required: true
          schema:
            type: string
          description: 조회하려는 후기의 향수의 이름
      responses:
        "200":
          description: 향수 코멘트 조회 (로그인 유저) 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "readUser success!"
              data:
                type: object

        "400":
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        "500":
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
  /{Name}/read:
    get:
      tags:
        - Perfume
      summary: 향수 코멘트 조회 (비로그인 유저)
      parameters:
        - name: Name
          in: path
          required: true
          schema:
            type: string
          description: 조회하려는 후기의 향수의 이름
      responses:
        "200":
          description: 향수 코멘트 조회 (비로그인 유저) 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "read success!"
              data:
                type: object

        "400":
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        "500":
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
  /{Name}/likePerfumes:
    patch:
      tags:
        - Perfume
      summary: 향수 찜하기 기능
      security:
        - BearerAuth: []
      parameters:
        - name: Name
          in: path
          required: true
          schema:
            type: string
          description: 찜하려는 향수의 이름
      responses:
        "200":
          description: 향수 찜하기 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "like success!"
              data:
                type: object

        "400":
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        "500":
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
  /perfumeList:
    get:
      tags:
        - PerfumeList
      summary: 취'향'목록 조회
      security:
        - BearerAuth: []
      parameters:
        - name: Keyword
          in: query
          description: 향수의 카테고리
          schema:
            type: array
            items:
              type: integer
          style: form
          explode: true
      responses:
        "200":
          description: 취'향'목록 조회 성공
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: array
                example: { "perfumeList_contentsData": [{ "name": "Eau Duelle", "imageUrl": "uploads/1.png", "status": "A", "keyword": "우드" }] }
