paths:
  /user/signup:
    put:
      tags:
        - User
      summary: 회원가입
      parameters:
      - name: signup
        in: body
        required: true
        schema:
          properties:
            id:
              type: string
              description: 유저 이메일
              example: swaggerTest@mail.com
            name:
              type: string
              description: 유저 이름
              example: swagger
            password:
              type: string
              description: 비밀번호 8자리 이상
              example: '12345678910'
            confirmPassword:
              type: string
              description: 비밀번호 확인 용도
              example: '12345678910'
            
      responses:
        '201':
          description: 회원 가입 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: object
                example: {
                  "id": "swaggerTest@mail.com",
                  "username": "swagger",
                  "password": "12345678910",
                  "confirmPassword":'12345678910'
                }
                
        '401':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 401
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON002
              message:
                type: string
                example: 존재하는 아이디 입니다.
        '422':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 422
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON003
              message:
                type: string
                example: 비밀번호가 일치하지 않습니다.
        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
  /user/login:
    post:
      tags:
        - User
      summary: 로그인
      parameters:
      - name: login
        in: body
        required: true
        schema:
          properties:
            id:
              type: string
              description: 유저 이메일
              example: swaggerTest@mail.com
            password:
              type: string
              description: 비밀번호 8자리 이상
              example: '12345678910'
            
      responses:
        '200':
          description: 로그인 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: object
                example: {
                  "id": "swaggerTest@mail.com",
                  "password": "12345678910"
                }
                
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
  /user/delete/{id}:
    delete:
      tags:
        - User
      summary: 회원 탈퇴
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        description: 탈퇴하려는 사용자의 ID
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
        description: Bearer token 작성하기
      responses:
        '200':
          description: 회원 탈퇴 성공
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              message:
                type: string
                example: "삭제되었습니다"
        '404':
          description: 사용자를 찾을 수 없음
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 404
              message:
                type: string
                example: "사용자를 찾을 수 없습니다"
        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
  /user/logout:
    post:
      tags:
        - User
      summary: 로그아웃
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
        description: "Bearer token 작성하기"

      responses:
        '200':
          description: 로그아웃 성공
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              message:
                type: string
                example: "로그아웃 성공"
        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.

